# Generated by Django 6.0.2 on 2026-02-22 18:01

import apps.transaction.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('officer_id', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('officer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_processed_new', to='core.usertype')),
                ('requester_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_requests_new', to='core.usertype')),
                ('status', models.ForeignKey(default=apps.transaction.models.default_pending_status_id, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_status_new', to='core.statuscode')),
            ],
            options={
                'db_table': 'CashOut',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('receiver_id', models.IntegerField(blank=True, null=True)),
                ('transactor_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receiver_type', models.ForeignKey(blank=True, db_column='receiver_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='core.usertype')),
                ('sender_type', models.ForeignKey(blank=True, db_column='sender_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='core.usertype')),
                ('transactor_type', models.ForeignKey(blank=True, db_column='transactor_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacted_transactions', to='core.usertype')),
            ],
            options={
                'db_table': 'Transaction',
                'indexes': [models.Index(fields=['sender_id', 'sender_type'], name='txn_sender_idx'), models.Index(fields=['receiver_id', 'receiver_type'], name='txn_receiver_idx')],
            },
        ),
    ]
