# Generated by Django 6.0.2 on 2026-02-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
    ]
