# Generated by Django 6.0.2 on 2026-02-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('average_time', models.IntegerField(blank=True, null=True)),
                ('appointment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_patient_limit', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.doctortype')),
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='personal.person')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='personal.person')),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(blank=True, db_column='person_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptionist_roles', to='personal.person')),
            ],
            options={
                'db_table': 'Receptionist',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='personal.doctor')),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_availabilities', to='core.weekday')),
            ],
            options={
                'db_table': 'DoctorAvailability',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'week_day'), name='pk_doctoravailability_doctor_weekday')],
            },
        ),
        migrations.CreateModel(
            name='DoctorOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='off_days', to='personal.doctor')),
            ],
            options={
                'db_table': 'DoctorOffDay',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='pk_doctoroffday_doctor_date')],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(blank=True, db_column='person_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officer_roles', to='personal.person')),
            ],
            options={
                'db_table': 'Officer',
                'indexes': [models.Index(fields=['person'], name='officer_person_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['person'], name='doctor_person_idx'),
        ),
        migrations.AddIndex(
            model_name='receptionist',
            index=models.Index(fields=['person'], name='receptionist_person_idx'),
        ),
    ]
