# Generated by Django 6.0.2 on 2026-02-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_laboratories', to='personal.person')),
            ],
            options={
                'db_table': 'Laboratory',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTestAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lab', models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.PROTECT, related_name='test_availabilities', to='business.laboratory')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.PROTECT, related_name='lab_availabilities', to='core.test')),
            ],
            options={
                'db_table': 'LaboratoryTestAvailability',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_pharmacies', to='personal.person')),
            ],
            options={
                'db_table': 'Pharmacy',
            },
        ),
        migrations.CreateModel(
            name='PharmacyMedicineAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_availabilities', to='core.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_availabilities', to='business.pharmacy')),
            ],
            options={
                'db_table': 'PharmacyMedicineAvailability',
            },
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['owner'], name='laboratory_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='laboratorytestavailability',
            constraint=models.UniqueConstraint(fields=('lab', 'test'), name='pk_labtestavail_lab_test'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['owner'], name='pharmacy_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacymedicineavailability',
            constraint=models.UniqueConstraint(fields=('medicine', 'pharmacy'), name='pk_pharmmedavail_medicine_pharmacy'),
        ),
    ]
