from django.urls import path
from .views import (
    DoctorTypeListView,
    CommonSymptompByDoctorTypeView,
    DoctorsAdviceByDoctorTypeView,
    BusinessPercentagesView,
    MedicineGenericListView,
    MedicinesByGenericView,
    MedicineCreateAPI,
    MedicineDetailAPI,
    TestAPI,
    TestDetailAPI,
    lab_tests_list_api,
    user_type_list_api,
    cashout_create_api,
    cashout_pending_list_api,
    cashout_accept_api,
    cashout_cancel_api,
    medicine_generic_list_create_api,
    dashboard_counts_api,
    profile_list_any_type_api, 
    profile_update_any_type_api,
)

urlpatterns = [
    path("doctor-types/", DoctorTypeListView.as_view(), name="doctor-types"),
    path("doctor-types/<int:doctor_type_id>/common-symptoms/",
         CommonSymptompByDoctorTypeView.as_view(),
         name="doctor-type-common-symptoms"),
    path("doctor-types/<int:doctor_type_id>/doctors-advice/",
         DoctorsAdviceByDoctorTypeView.as_view(),
         name="doctor-type-doctors-advice"),
    path("business/percentages/", BusinessPercentagesView.as_view(), name="business-percentages"),
    path("medicine-generics/", MedicineGenericListView.as_view(), name="medicine-generics"),
    path("medicine-generics/<int:generic_id>/", MedicinesByGenericView.as_view(), name="medicines-by-generic"),
    path("medicines/", MedicineCreateAPI.as_view(), name="medicine-create"),
    path("medicines/<int:pk>/", MedicineDetailAPI.as_view(), name="medicine-detail"),
    path("tests/", TestAPI.as_view(), name="test-create"),
    path("tests/<int:pk>/", TestDetailAPI.as_view(), name="test-detail"),
    path("lab-tests/", lab_tests_list_api, name="lab_tests_list_api"),
    path("user-types/", user_type_list_api),
    path("cashout/", cashout_create_api, name="cashout_create_api"),
    path("cashout/pending/", cashout_pending_list_api, name="cashout_pending_list_api"),
    path("cashout/<int:request_id>/accept/", cashout_accept_api, name="cashout_accept_api"),
    path("cashout/<int:request_id>/cancel/", cashout_cancel_api, name="cashout_cancel_api"),
    path("medicine-generic/", medicine_generic_list_create_api),
    path("dashboard-counts/", dashboard_counts_api),
    path("profile/all/", profile_list_any_type_api),
    path("profile/update/", profile_update_any_type_api),
]
