# Generated by Django 6.0.2 on 2026-02-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('type', models.CharField(blank=True, help_text='Appointment afspraak type, e.g., Report Analysis, Follow-up, New Patient', max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='personal.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='personal.patient')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statuscode')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Prechecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.TextField(blank=True, null=True)),
                ('pulse', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('temperature', models.TextField(blank=True, null=True)),
                ('spo2', models.TextField(blank=True, null=True)),
                ('heart', models.TextField(blank=True, null=True)),
                ('lungs', models.TextField(blank=True, null=True)),
                ('abd', models.TextField(blank=True, null=True)),
                ('anemia', models.TextField(blank=True, null=True)),
                ('jaundice', models.TextField(blank=True, null=True)),
                ('cyanosis', models.TextField(blank=True, null=True)),
                ('rbs', models.TextField(blank=True, null=True)),
                ('bmi', models.TextField(blank=True, null=True)),
                ('bmr', models.TextField(blank=True, null=True)),
                ('family_disease_history', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prechecked_records', to='prescription.appointment')),
            ],
            options={
                'db_table': 'Prechecked',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dx', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('prechecked', models.BooleanField(default=False)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('next_visit', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prescription.appointment')),
                ('prechecked_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prescription.prechecked')),
            ],
            options={
                'db_table': 'Prescription',
            },
        ),
        migrations.CreateModel(
            name='PrescribedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_tests', to='core.test')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='prescription.prescription')),
            ],
            options={
                'db_table': 'PrescribedTest',
            },
        ),
        migrations.AddField(
            model_name='prechecked',
            name='prescription_id',
            field=models.ForeignKey(blank=True, db_column='prescription_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prescription.prescription'),
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_reports', to='business.laboratory')),
                ('prescribed_test', models.OneToOneField(db_column='prescribed_test_id', on_delete=django.db.models.deletion.PROTECT, related_name='report', to='prescription.prescribedtest')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statuscode')),
            ],
            options={
                'db_table': 'TestReport',
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_process', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='prescription.prescription')),
            ],
            options={
                'db_table': 'PrescribedMedicine',
                'indexes': [models.Index(fields=['prescription'], name='prescmed_prescription_idx')],
            },
        ),
    ]
